; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = nodemcuUSB

[env:nodemcuUSB]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
upload_protocol = esptool
upload_speed = 921600

lib_deps = 
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.9.0
	adafruit/Adafruit GFX Library@^1.11.5
	adafruit/Adafruit SSD1306@^2.4.7
	bblanchon/ArduinoJson@^7.4.2
	xreef/PCF8574 library@^2.4.0

[env:nodemcuOTA]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = ${env:nodemcuUSB.monitor_speed}
board_build.filesystem = littlefs

upload_protocol = espota
upload_port = esp-thermo.local
upload_flags = --auth=1234

lib_deps = ${env:nodemcuUSB.lib_deps}

; [env:esp8266_fallback]
; platform = espressif8266
; board = nodemcu
; framework = arduino
; extra_scripts = pre:upload_fallback.py
; lib_deps = ${env:nodemcuUSB.lib_deps}
